# Generated by Django 4.2.5 on 2023-10-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCoursrMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('l', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practial'), ('S', 'Skill')], max_length=10)),
                ('type', models.BooleanField()),
                ('section', models.CharField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.faculty')),
            ],
            options={
                'db_table': 'facultycoursemapping_table',
            },
        ),
    ]
