# Generated by Django 4.2.5 on 2023-11-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='eid',
            new_name='id',
        ),
    ]
